name: Linux

on: [push]

jobs:
    build-linux:
        strategy:
            matrix:
                qt_version: [5.15.2, 6.5.2]

        runs-on: ubuntu-latest
        name: build-linux-qt${{matrix.qt_version}}

        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install Qt
          uses: jurplel/install-qt-action@v3
          with:
              version: ${{matrix.qt_version}}
              cache: true
              cache-key-prefix: QtCache

        # Actually needed for Qt6
        - name: Install dependencies for "xcb" Qt plugin
          run: |
              sudo apt-get -y install libxcb-cursor0

        - name: Install OpenCascade
          run: |
              sudo apt-get -y install libocct-data-exchange-dev libocct-draw-dev occt-misc
              sudo apt-get -y install libtbb-dev
              sudo apt-get -y install libxi-dev

        - name: Install Assimp
          run: |
              sudo apt-get -y install libassimp-dev

        - name: Build
          run: |
              mkdir ${{github.workspace}}/build
              cd ${{github.workspace}}/build
              cmake --version
              cmake .. \
                    -DMayo_BuildTests=ON \
                    -DMayo_BuildPluginAssimp=ON
              cmake --build . \
                    --config Release \
                    --parallel `nproc`

        - name: Execute Unit Tests
          working-directory: ${{github.workspace}}/build
          env:
              DISPLAY: :0
          run: |
              # Install french locale for testing case
              echo "fr_FR ISO-8859-15" | sudo tee -a /etc/locale.gen
              sudo locale-gen
              localectl list-locales
              # Start X11 display server
              Xvfb $DISPLAY -screen 0 1280x1024x24 &
              sleep 5s
              # Run tests
              ./mayo --runtests
